workflows:
  ios-workflow:
    name: iOS Build - Estación HOMIES
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.estacionhomies.app"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...) # Añadir después
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...) # Añadir después
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...) # Añadir después
        CERTIFICATE_PRIVATE_KEY: Encrypted(...) # Añadir después
      node: 18
      xcode: 15.0
      cocoapods: default
    
    scripts:
      - name: Install Node dependencies
        script: |
          npm install
      
      - name: Build web assets
        script: |
          npm run build
      
      - name: Sync Capacitor to iOS
        script: |
          npx cap sync ios
      
      - name: Set up keychain for code signing
        script: |
          keychain initialize
      
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ios/App/App.xcarchive
    
    publishing:
      email:
        recipients:
          - tu-email@ejemplo.com # Cambiar por tu email
        notify:
          success: true
          failure: true
      
      # Descomentar para subir a TestFlight automáticamente
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true
      #   beta_groups:
      #     - Internal Testers

  # Workflow simplificado para testing sin firma
  ios-workflow-unsigned:
    name: iOS Build (Sin Firma) - Solo Testing
    instance_type: mac_mini_m1
    max_build_duration: 30
    
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 22
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Check Node version
        script: |
          node --version
          npm --version
      
      - name: Install dependencies
        script: |
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          # Instalar Capacitor CLI globalmente para asegurar compatibilidad
          npm install -g @capacitor/cli@8.0.0
      
      - name: Verify Capacitor installation
        script: |
          cap --version
          which cap
      
      - name: Build web and sync iOS
        script: |
          npm run build
          cap sync ios
      
      - name: Build for simulator (using Swift Package Manager)
        script: |
          xcodebuild -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath ios/build \
            -destination 'platform=iOS Simulator,name=iPhone 15'
    
    artifacts:
      - ios/build/Build/Products/Debug-iphonesimulator/*.app
